stages:
  - build
  - test

build-job:
  stage: build
  environment:
    - login: builder
    - password: $PRIVATE_PASSWORD
  tags:
    - gitlab-build
    - build
  script:
    - echo "Start build job"
    - build-script.sh $login $password
  artifacts:
    paths:
      - build

test-job:
  stage: test
  tags:
    - gitlab-test
    - test
  script:
    - echo "Start test job"
    - test-script.sh
  artifacts:
    paths:
      - coverage
      - coverage-html
